server:
  mode: debug
  port: 8080

mysql:
  host: localhost
  port: 3306
  username: root
  password: prynnekey
  database: gin-mall # 要连接的具体数据库

redis:
  addr: 172.26.177.28:6379
  password: 123456
  db: 0

email:
  validEmail: http://localhost:8080/#/vaild/email/
  ValidEmail: smtp.qq.com
  SmtpHost: smtp.qq.com
  SmtpEmail: 你的邮箱
  SmtpPass: 你的邮箱的通信码
